import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./components/App/App";
import { createStore } from "redux";
import addMovies from "./services/reducers";
const store = createStore(addMovies);
const app = <App store={store} />;
const root = document.getElementById("root");
console.log("Store", store);
console.log("Before State", store.getState());
store.dispatch({ type: "ADD_MOVIES", movies: [{ name: "Superman" }] });
console.log("After State", store.getState());
ReactDOM.render(app, root);
