import React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./components/App/App";
import { createStore } from "redux";
import rootReducer from "./services/reducers";
const store = createStore(rootReducer);
const app = <App store={store} />;
const root = document.getElementById("root");
ReactDOM.render(app, root);
